version: 2.1

workflows:
  version: 2
  build_all:
    jobs:
      - linux

jobs:
  linux:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Setup Dependencies
          command: |
            apt-get update -y
            DEBIAN_FRONTEND="noninteractive" apt-get install -y gnupg2 software-properties-common tzdata python3 python3-pip
            apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
            add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
            apt-get update -y
            apt-get install -y r-base
            pip3 install launchdarkly-server-sdk
            R -e "install.packages('reticulate')"
      - run:
          name: Run Demo
          command: Rscript hello.r
