version: 2.1

workflows:
  version: 2
  build_all:
    jobs:
      - linux:
          context: hello-world-demos

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: main
    jobs:
      - linux:
          context: hello-world-demos
jobs:
  linux:
    docker:
      - image: cimg/base:2024.06
    steps:
      - checkout
      - run:
          name: Setup Dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y gnupg2 software-properties-common tzdata pip r-base
            pip install launchdarkly-server-sdk
            sudo R -e "install.packages('reticulate')"

      - run:
          name: Run Demo
          command: |
            export LAUNCHDARKLY_SDK_KEY=${LD_HELLO_WORLD_SDK_KEY}
            export LAUNCHDARKLY_FLAG_KEY=${LD_HELLO_WORLD_FLAG_KEY_WITH_TRUE_VALUE}

            Rscript main.r | tee output.txt
            grep -q "feature flag evaluates to true" output.txt || (echo "Flag did not evaluate to expected true value" && exit 1)
