name: Build and run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'
  push:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed if using OIDC to get release secrets.

    env:
      RETICULATE_PYTHON: ${{ github.workspace }}/.venv/bin/python

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.8

      - uses: r-lib/actions/setup-r@a51a8012b0aab7c32ef9d19bf54da93f3254335e

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev

      - name: Install dependencies
        run: |
          R -e 'install.packages("reticulate")'
          python -m venv .venv
          .venv/bin/pip install launchdarkly-server-sdk

      - uses: launchdarkly/gh-actions/actions/verify-hello-app@verify-hello-app-v2.0.1
        with:
          use_server_key: true
          role_arn: ${{ vars.AWS_ROLE_ARN }}
          command: Rscript main.r
